### PR TITLE
Add gzip support for #3

### PR DESCRIPTION
**Pull request by a86c6f7964**

### CODE REVIEW

**Comment by a86c6f7964** [comment]
It doesn't look like this got linked to #3 correctly

**Comment by shribigb** [comment]
I gave this pull request a try and I noticed that its missing few seconds of data. Also most of the time last message is  truncated at the end of the file.

**Comment by a86c6f7964** [comment]
Is that just a general problem? I am not really sure why it would be the case given that its just wrapping an existing pipe

**Comment by a86c6f7964** [comment]
i am seeing that behavior as well. i wonder if there is a missing flush that was still working because of the syswrite call

**Comment by shribigb** [comment]
That last fix seems to fix the problem. Now I dont see missing log lines as well as truncated files. Thanks a lot.

**Comment by a86c6f7964** [comment]
Great. Works well for me too

**Comment by suyograo** [comment]
@a86c6f7964 this looks great! can you please add tests to validate this behavior?

**Comment by a86c6f7964** [comment]
@suyograo I do not know much about testing ruby stuff. maybe if someone else can add tests? it is mostly tested by any of the existing logical tests since all it does is wrap the gzip stream around the file stream that already exists.

**Comment by suyograo** [comment]
@a86c6f7964 sorry about the delays here.. can you rebase please?

**Comment by a86c6f7964** [comment]
okay

**Comment by a86c6f7964** [comment]
I rebased it, fixed the conflicts, and it looks like its passing the tests.

**Comment by a86c6f7964** [comment]
does my rebase work?

**Pull request merged**
