### PR TITLE
Fix a synchronization issue when doing file rotation

### PR DESCRIPTION
**Pull request by ph**
Added a `synchronize` block when trying to fetch the current size of the
temp file, this method could have been call when doing a file rotation
and throw `OError: Connection reset by peer` Fixes: #15

### CODE REVIEW

**Comment by ph** [comment]
@purbon Can you look at this?

**Comment by purbon** [comment]
@ph looking at this.

**Comment by purbon** [comment]
@ph code looks good, can we add a test to cover this situation?

**Comment by ph** [comment]
@purbon Its a race condition how would you test this?

**Comment by purbon** [comment]
@ph can you describe the condition, then we might be able to workout  a test. I mean, I guess you did that fix, because you were somehow able to reproduce the condition, isn't? which was your process?

**Comment by ph** [comment]
The condition was that two different threads was competing to access the same File handle.
One of the thread was doing a periodic rotation of the file and the writing thread was looking at the size of the file to know if we need to rotate it. 

Since the file was being 'moved' the writer would throw a `OError: Connection reset by peer` all the other access to the file were alreading using a shared lock except the *file size check*, This PR add the lock to this method.

This is a race condition and it isa  bit hard to reproduce in a local environment, Some people tried the patch and it fixed their problem.

**Comment by ph** [comment]
If you want any idea how we could add a test for that behavior I would really like to know how to do it.

**Comment by ph** [comment]
edited last comment since it didnt make any sense :)

**Comment by purbon** [comment]
you could see an initial proposal of test at https://github.com/ph/logstash-output-s3/pull/1 , not perfect, but already more than not having anything ... looking forward to iterate them :P

**Comment by ph** [comment]
@purbon I have added your specs and it LGTM and I will release it. TIL.

**Comment by purbon** [comment]
@ph Cool, I know they are not perfect, but at less is something. Keep in mind to rebase the commits, especially the merge commits, looks not clever to have in the history, don't you think?

**Comment by ph** [comment]
dont worry I'll squash it.

**Pull request closed without merging**
