### PR TITLE
clarify docs and fix grammar errors

### PR DESCRIPTION
**Pull request by jasonrhaas**

### CODE REVIEW

**Comment by pctj101** [comment]
haha you too? #28

**Comment by jasonrhaas** [comment]
@pctj101 maybe we should combine our fixes into a single pull request, if that makes sense.

**Comment by purbon** [comment]
Thanks a lot for your contribution @jasonrhaas , in order to move forward with your PR is going to be necessary to sign the CLA agreement, you can find more information at https://www.elastic.co/contributor-agreement.
 
Looking forward to get this in,

**Comment by jasonrhaas** [comment]
CLA has been signed

**Comment by jasonrhaas** [comment]
@purbon CLA has been signed -- let me know if you need anything else

**Comment by jordansissel** [comment]
LGTM

**Pull request closed without merging**
