### PR TITLE
Handle file not found exception on S3 upload

### PR DESCRIPTION
**Pull request by marcinc**
This PR addresses https://github.com/logstash-plugins/logstash-output-s3/issues/143:
* Handle uploader missing file exception.
* Wait `TIME_BEFORE_RETRYING_SECONDS` before each file upload retry.

### CODE REVIEW

**Comment by ph** [comment]
Good find! @marcinc Can you sign the CLA, I will take a look after.

**Comment by marcinc** [comment]
CLA signed. Cheers.

**Comment by ph** [comment]
Code LGTM, I am OK to add the handling of this specific case.


> It could be potentially a result of some race condition when LS crash happens whereby file gets removed from disk before recovery threadpool gets to process it? In such situation any attempt to upload non-existent file to S3 would fail with exception which in turn logs error and retry immediately. Note: Uploader currently doesn't utilise TIME_BEFORE_RETRYING_SECONDS even though it's defined.

I am still trying to find how this case can happen, I don't think we could have a race, the only thing I could see is the file was deleted externally before the process was able to upload it?


Do you have multiple S3 outputs that shares the same *temporary directory*? Or do you have multiple Logstash instances that use the same *temporary directory*?

**Comment by marcinc** [comment]
@ph temp files aren't touched by anything else so scenario where they get deleted externally is very unlikely.  

> Do you have multiple S3 outputs that shares the same temporary directory? Or do you have multiple Logstash instances that use the same temporary directory?

I run multiple s3 outputs (3 in this case) and all of those share the same temp directory.

Could it be that recovery thread pool picks up only after the periodic check happened which can potentially remove those files earlier?

**Comment by ph** [comment]
> I run multiple s3 outputs (3 in this case), and all of those share the same temp directory.

I think the following happen, the three outputs share the same temporary directory, and all of them have the *restore from a crash* option. So all of them read for the temporary directory and try to resume the upload operation. One of them completes the upload of the file before the others, when the other try to upload the document the file will be deleted.

So I think we should merge this PR and create another issue to make sure the temporary directory is locked to one s3 output.


Also depending on your configuration, you might not need to have multiple s3 outputs, maybe you can use a dynamic prefix instead. Assuming you are sending everything to the same bucket.

**Comment by marcinc** [comment]
@ph yeah, I think this makes total sense. I'll try to experiment with that. Will report back on the findings.

**Comment by marcinc** [comment]
@ph your theory proved to be correct. Combined multiple s3 outputs into a single one solved the issue. 

> So I think we should merge this PR and create another issue to make sure the temporary directory is locked to one s3 output.

👍  to the above :)

**Pull request merged**
