### PR TITLE
feat: support ONEZONE_IA

### PR DESCRIPTION
**Pull request by max-wittig**

### CODE REVIEW

**Comment by max-wittig** [comment]
@karenzone @colinsurprenant Could you please have a look?

**Comment by colinsurprenant** [comment]
Thanks for your contribution @max-wittig - this seems like a no-brainer to add! LGTM.
To be able to push a new plugin version we also need to bump the version (to 4.2.0) in `logstash-output-s3.gemspec` and add to the `CHANGELOG.md`. Would you be able to also add this to the PR?

Once @karenzone has reviewed docs related changes we'll merge and push the new plugin version.

**Comment by max-wittig** [comment]
@colinsurprenant Thanks for the review 👍. I've pushed a new commit with the version bump.

**Comment by colinsurprenant** [comment]
v4.2.0 published! thanks @max-wittig @karenzone !

**Comment by max-wittig** [comment]
Thanks  @colinsurprenant :+1: 

Any idea, when this new version will be used by ELK?

**Comment by karenzone** [comment]
It will be picked up in our next minor release 7.5.2. You can update it already.
Thanks again for contributing the updates!

**Pull request merged**
