### PR TITLE
Clarify documentation regarding size_file and time_file

### PR DESCRIPTION
**Pull request by pctj101**
Reworded the comments to make it easier to read / understand.

### CODE REVIEW

**Comment by purbon** [comment]
Thanks a lot for your contribution @pctj101 , in order to move forward with your PR is going to be necessary to sign the CLA agreement, you can find more information at https://www.elastic.co/contributor-agreement.

**Comment by pctj101** [comment]
Cla signed

**Comment by ph** [comment]
lgtm

**Comment by purbon** [comment]
@pctj101 due to last days changes, you might need to rebase this PR. Can you do that? I'm sorry it took to long to come back here, so many thing going on and so few hours in a day. Thanks for your understanding.

**Comment by pctj101** [comment]
Lemme see what I can do

**Comment by pctj101** [comment]
Rebased code

**Pull request closed without merging**
