### PR TITLE
Support S3 v4 signatures

### LINKED ISSUE #51: Support v4 Signature
We need to resolve errors like `"Error: Requests specifying Server Side Encryption with AWS KMS managed keys require AWS Signature Version 4"`. We can fix this by adding an option to instantiate the library with `AWS::S3::Client.new(:s3_signature_version => :v4)`.

### PR DESCRIPTION
**Pull request by andrewvc**
Fixes #51

### CODE REVIEW

**Comment by ph** [comment]
code lgtm, not sure why jenkins didn't kick in?

**Comment by ph** [comment]
I havent tested with a real s3 bucket but according to the documentation this should work.

**Comment by andrewvc** [comment]
@ph I did run the integration specs myself FWIW. Waiting for @PhaedrusTheGreek to test this against one of those unicorn v4 buckets.

**Comment by andrewvc** [comment]
@ph is your LGTM enough to merge this? I'm good on merging it as is without full integration testing.

**Comment by ph** [comment]
yes, I am okay to merge this! :)

**Pull request closed without merging**
