### PR TITLE
Patch to address the validation bug when S3 bucket has policies that require encryption headers in place.

### PR DESCRIPTION
**Pull request by frite**
Hi all,
I wrote a small patch and updated the tests to address issue 146 (https://github.com/logstash-plugins/logstash-output-s3/issues/146). Feel free to review it and leave comments if you want something changed.
Regards,
Manolis

### CODE REVIEW

**Comment by karmi** [comment]
Hi @frite, we have found your signature in our records, but it seems like you have signed with a different e-mail than the one used in yout Git [commit](https://github.com/logstash-plugins/logstash-output-s3/pull/155.patch). Can you please add both of these e-mails into your Github profile (they can be hidden), so we can match your e-mails to your Github profile?

**Comment by frite** [comment]
@karmi My PR was failing, I tried building the master as well and it failed for 2 of the builds. Looks like it's missing ` uninitialized constant LogStash::Environment`. Will look into it and expand the scope of this PR.

**Comment by jordansissel** [comment]
@frite the Logstash::Environment failure is due to a bug in Logstash-core branches.

Issue: https://github.com/elastic/logstash/issues/8096

PR is in-progress: https://github.com/elastic/logstash/pull/8097

**Comment by frite** [comment]
@jordansissel Should have checked the issues there first :) Looks cool then. I'll do a cleanup of my PR then tomorrow and leave it pending until issue/PR is resolved. Thanks for letting me know.

**Comment by jordansissel** [comment]
@frite no worries, thank you for  working on this :)

**Comment by frite** [comment]
Closed, reopened PR to trigger Travis build

**Comment by frite** [comment]
Builds are passing now, happy days. @jordansissel Can you review it when you get a chance? :)

**Comment by frite** [comment]
Hey @jordansissel, @karmi any progress on this? :)

**Comment by frite** [comment]
Guys, any update on this?

**Comment by jordansissel** [comment]
Tests pass, but I haven't tested manually. It sounds like this is confirmed to solve #146 by @frite, so I am OK merging.

**Comment by frite** [comment]
Cheers guys :)

**Pull request closed without merging**
