### PR TITLE
Add "bucket-owner-full-control" canned ACL

### PR DESCRIPTION
**Pull request by mool**
Add support for the `bucket-owner-full-control` ACL. It's very useful when you are writing files in a bucket owned by a different AWS account.

### CODE REVIEW

**Comment by mool** [comment]
I've signed the CLA twice, but I still see the the check failing.

**Comment by aresen** [comment]
This looks good, any chance it'll be included soon?

**Comment by sarneaud** [comment]
Thanks for this, but in our case we need `bucket-owner-read`.  Here are all the ACLs available now:
https://docs.aws.amazon.com/AmazonS3/latest/dev/acl-overview.html#canned-acl

**Comment by jsvd** [comment]
done in https://github.com/logstash-plugins/logstash-output-s3/pull/158

**Pull request closed without merging**
