### PR TITLE
Clarify endpoint documentation

### PR DESCRIPTION
**Pull request by Pectojin**
Clarified the need to explicitly declare HTTP or HTTPS in the endpoint URL.

### CODE REVIEW

**Comment by karenzone** [comment]
@Pectojin  Thank you for your contribution. We are looking forward to reviewing it.  Before we can, we need you to sign our CLA.  Please feel free to contact me if you have questions.  Thanks!

**Comment by Pectojin** [comment]
Thanks for the heads up, I thought I had filled it out back when I made the PR but it must have slipped my mind.

Could you trigger the CLA check to re-run on your CI?

**Comment by karenzone** [comment]
@Pectojin Thanks for your quick response.  
It looks like the commits might be associated with a different email address. Could you add the second email address to your Github profile?  (I think you can hide the address if you want to.) Thanks!

**Comment by Pectojin** [comment]
Ah, yeah that makes sense, I used the wrong email in the signing. I've added that new email to the account so it should link up now.

**Comment by karenzone** [comment]
Thank you! The CLA update is not triggering here, but I have verified.

**Comment by karenzone** [comment]
@Pectojin  Thank you for helping us make our docs better! We appreciate your contribution.

**Pull request merged**
