### PR TITLE
Refactoring, Dynamic prefix and AWS v2 (extended)

### PR DESCRIPTION
**Pull request by nevins-b**
This is a continuation of @ph's awesome work in #102 

This takes into account most of the logic and grammatical changes mentioned in the review of that pull request. It does not do the renaming or deprecation of options.

### CODE REVIEW

**Comment by ph** [comment]
@nevins-b Can you sign the CLA? 

Would you mind doing step 2 of the contributing guide? https://github.com/elasticsearch/logstash/blob/master/CONTRIBUTING.md#contribution-steps

**Comment by nevins-b** [comment]
@ph Should be all set.

**Comment by karmi** [comment]
Hi @nevins-b, we have found your signature in our records, but it seems like you have signed with a different e-mail than the one used in yout Git [commit](https://github.com/logstash-plugins/logstash-output-s3/pull/105.patch). Can you please add both of these e-mails into your Github profile (they can be hidden), so we can match your e-mails to your Github profile?

**Comment by nevins-b** [comment]
@karmi Added.

**Comment by ph** [comment]
I've merged your commit into #102, there is 7 integrations test that are currently failling taking a look.

**Pull request closed without merging**
