### PR TITLE
Add more S3 bucket ACLs

### LINKED ISSUE #76: S3 output Plugin does not supports canned_acl => "bucket_owner_full_control"
We need the Outputted file from Logstash to S3 to be fully controlled by bucket owner .

Currently only Below Options are available : 

canned_acl => "private"                  (optional. Options are "private", "public_read", "public_read_write", "authenticated_read". Defaults to "private" )

We should add support for  "bucket_owner_full_control"

### PR DESCRIPTION
**Pull request by MrPrimate**
There are more canned ACL's available, and I would like to use them when storing logs.

Expands #152 Resolves #76

### CODE REVIEW

**Comment by randomvariable** [comment]
Is there a status update on this?

**Comment by jordansissel** [comment]
@randomvariable what status are you looking for? I don't think anyone's reviewed this, so it waits for that review (and testing, etc).

If you have energy to help PR in its journey, it could be helpful if you test this and report your experience.

**Comment by bmandrade** [comment]
Hey guys, I used logstash s3 output to put objects in a client aws s3 bucket, but I had to use this patch for the client be able to get the objects in it's own bucket.

Besides that, I also needed to add the `PutObjectAcl` action to aws policy, not just `PutObject` as the documentation said.

If you need more info, let me know, to help moving this PR forward.

cc:
@jordansissel 
@MrPrimate  (Thanks a lot for this one 👍 )

**Comment by jsvd** [comment]
Many thanks for the well put PR @MrPrimate

**Pull request merged**
